/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_polymtl_inf2990_InterfaceJava */

#ifndef _Included_ca_polymtl_inf2990_InterfaceJava
#define _Included_ca_polymtl_inf2990_InterfaceJava
#ifdef __cplusplus
extern "C" {
#endif
#undef ca_polymtl_inf2990_InterfaceJava_TEMPS_INTER_AFFICHAGE
#define ca_polymtl_inf2990_InterfaceJava_TEMPS_INTER_AFFICHAGE 20L
/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_initialiserOpenGL
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1initialiserOpenGL
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_libererOpenGL
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1libererOpenGL
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_dessinerOpenGL
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1dessinerOpenGL
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_redimensionnerFenetre
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1redimensionnerFenetre
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_animer
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1animer
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_zoomIn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1zoomIn
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_zoomOut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1zoomOut
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    obtenirAffichagesParSeconde
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_obtenirAffichagesParSeconde
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_executerTests
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1executerTests
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_deplacerXY
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1deplacerXY
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_zoomerInElastique
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1zoomerInElastique
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_zoomerOutElastique
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1zoomerOutElastique
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_initialiserRectangleElastique
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1initialiserRectangleElastique
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_mettreAJourRectangleElastique
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1mettreAJourRectangleElastique
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_terminerRectangleElastique
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1terminerRectangleElastique
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_selectionClick
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1selectionClick
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_selectionRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1selectionRectangle
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_rotationSelection
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1rotationSelection
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_creationObject
 * Signature: (IDDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1creationObject
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_deleteSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1deleteSelection
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_deplacementSelection
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1deplacementSelection
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_duplicationSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1duplicationSelection
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_viderSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1viderSelection
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_viderArbre
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1viderArbre
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_convertirCoordonneesSouris
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1convertirCoordonneesSouris
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_enregistrerXml
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1enregistrerXml
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_chargerXml
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1chargerXml
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_facteurSelection
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1facteurSelection
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_recevoirInformation
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1recevoirInformation
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_manipulerObjet
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1manipulerObjet
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_clickBalle
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1clickBalle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_creerFleche
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1creerFleche
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_effacerFleche
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1effacerFleche
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierFleche
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierFleche
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_changerMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1changerMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirFrictionSol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirFrictionSol
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierFrictionSol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierFrictionSol
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirFrictionSable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirFrictionSable
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierFrictionSable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierFrictionSable
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirRebondMur
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirRebondMur
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierRebondMur
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierRebondMur
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirAccelerationBonus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirAccelerationBonus
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierAccelerationBonus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierAccelerationBonus
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirTailleEditionHauteur
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirTailleEditionHauteur
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierTailleEditionHauteur
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierTailleEditionHauteur
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirTailleEditionLargeur
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirTailleEditionLargeur
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierTailleEditionLargeur
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierTailleEditionLargeur
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_forcerSauvergardeConfig
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1forcerSauvergardeConfig
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierFlecheTouche
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierFlecheTouche
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_verifierVictoire
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1verifierVictoire
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_effacerFichierXml
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1effacerFichierXml
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_chargerFichierJoueur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1chargerFichierJoueur
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_chargerFichierTournoi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1chargerFichierTournoi
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_enregistrerFichierJoueur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1enregistrerFichierJoueur
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_enregistrerFichierTournoi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1enregistrerFichierTournoi
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_ajouterJoueur
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1ajouterJoueur
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_ajouterTournoi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1ajouterTournoi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirToucheClavier
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirToucheClavier
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierToucheClavier
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierToucheClavier
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirOptionClavier
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirOptionClavier
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierOptionClavier
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierOptionClavier
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNomsParcours
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNomsParcours
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNomsTournois
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNomsTournois
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNombreTournois
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNombreTournois
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_modifierFicheTournoi
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1modifierFicheTournoi
  (JNIEnv *, jclass, jstring, jstring, jstring, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_changerVue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1changerVue
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_ajouterParcoursATournoi
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1ajouterParcoursATournoi
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_initialiserSon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1initialiserSon
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_getTypeVue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1getTypeVue
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_deplacerLibre
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1deplacerLibre
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1play
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1stop
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_ajusterVolumeSon
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1ajusterVolumeSon
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_ajusterVolumeMusique
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1ajusterVolumeMusique
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_musiqueSuivante
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1musiqueSuivante
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_musiquePrecedente
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1musiquePrecedente
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_musiqueMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1musiqueMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_tournerCamera
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1tournerCamera
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_orbiterCamera
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1orbiterCamera
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirFrappes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirFrappes
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNomJoueur
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNomJoueur
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_convertirCoordonneesSouris2
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1convertirCoordonneesSouris2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_sauvegarderMultijoueur
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1sauvegarderMultijoueur
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_chargerMultijoueur
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1chargerMultijoueur
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_mute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1mute
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNomMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNomMap
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirPardeMap
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirPardeMap
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNombreJoueursTableauMeilleurScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNombreJoueursTableauMeilleurScore
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNombreParcoursTableauMeilleurScore
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNombreParcoursTableauMeilleurScore
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_obtenirNomsParcoursTableauMeilleurScore
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1obtenirNomsParcoursTableauMeilleurScore
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_initialiserListesAffichage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1initialiserListesAffichage
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_InterfaceJava
 * Method:    fctC_effacerFichierJoueur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_InterfaceJava_fctC_1effacerFichierJoueur
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
